### ISSUE TITLE
One test case fails to run (the 2652 test cases pass just fine)

### ISSUE THREAD

**Issue by pietersv** [SheetJS/test_files#2]
This is an impressively professional test suite. Minor, not urgent, just documenting one case that fails while details are fresh:
- Cloned new fork of master project  `git clone https://github.com/SheetJS/js-xlsx.git`
- Ran `npm install`
- Ran `npm run-script test`

The tester chugs and stops on one particular test case (`it("should have comment as part of cell properties")`) with the error below.  

After commenting out that one test case on lines 500-514 of test.js the test suite seems fine, returning `2652 passing, 597 pending`.   So I think this is a non issue for now, relevant only later for testing future pull requests.

```
2652 passing (18s)
  597 pending
  1 failing

  1) parse features should have comment as part of cell properties:
     Error: ENOENT, no such file or directory './test_files/apachepoi_SimpleWithComments.xlsx'
      at Object.fs.openSync (fs.js:432:18)
      at Object.fs.readFileSync (fs.js:289:15)
      at readSync (/Users/me/Exp/js-xlsx/xlsx.js:5155:36)
      at Object.readFileSync [as readFile] (/Users/me/Exp/js-xlsx/xlsx.js:5163:9)
      at Context.<anonymous> (/Users/me/Exp/js-xlsx/test.js:503:13)
      at callFn (/Users/me/Exp/js-xlsx/node_modules/mocha/lib/runnable.js:251:21)
      at Test.Runnable.run (/Users/me/Exp/js-xlsx/node_modules/mocha/lib/runnable.js:244:7)
      at Runner.runTest (/Users/me/Exp/js-xlsx/node_modules/mocha/lib/runner.js:374:10)
      at /Users/me/Exp/js-xlsx/node_modules/mocha/lib/runner.js:452:12
      at next (/Users/me/Exp/js-xlsx/node_modules/mocha/lib/runner.js:299:14)
      at /Users/me/js-xlsx/node_modules/mocha/lib/runner.js:309:7
      at next (/Users/me/Exp/js-xlsx/node_modules/mocha/lib/runner.js:248:23)
      at Object._onImmediate (/Users/me/Exp/js-xlsx/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:345:15)


make: *** [test] Error 1

npm ERR! xlsx@0.7.12 test: `make test`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the xlsx@0.7.12 test script.
npm ERR! This is most likely a problem with the xlsx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make test
npm ERR! You can get their info via:
npm ERR!     npm owner ls xlsx
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "run-script" "test"
npm ERR! cwd /Users/me/Exp/js-xlsx
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/me/Exp/js-xlsx/npm-debug.log
npm ERR! not ok code 0
```

**Comment by SheetJSDev** [comment]
@gradualstudent good catch!  I can reproduce on a clean checkout.

Strange thing is that the file exists (manual verification as well as testing with `fs.existsSync`) and the CI test succeeded earlier today, according to https://travis-ci.org/SheetJS/js-xlsx/jobs/51853581 .  Will have to do some more digging

**Comment by SheetJSDev** [comment]
We will make a more comprehensive test file.  In the meanwhile the js-xlsx test will be changed to check if the file exists first.
